import fs from "node:fs";
import path from "node:path";
import chalk from "chalk";
import { createLlamaBridge } from "../memory/llama-bridge.js";
import { getMemoryStore, type MemoryStore } from "../memory/memory-store.js";

/**
 * [Phase 21] Autonomous Skill Factory
 * Automatically detects patterns in swarm activity and generates portable .aizen skills.
 */
export class SkillFactory {
	private store: MemoryStore;
	private llama = createLlamaBridge();
	private projectDir: string;

	constructor(projectDir: string) {
		this.projectDir = projectDir;
		this.store = getMemoryStore(projectDir);
	}

	/**
	 * Analyzes activity logs (synapses) to find repetitive patterns.
	 */
	async detectPatterns(): Promise<any[]> {
		console.log(chalk.cyan(`[SkillFactory] Analyzing neural activity for automation patterns...`));

		const patterns = this.store
			.getDb()
			.prepare(`
				SELECT action, target, COUNT(*) as frequency
				FROM synapses
				WHERE action NOT IN ('LOGIN', 'INIT') 
				GROUP BY action, target
				HAVING frequency >= 3
				ORDER BY frequency DESC
				LIMIT 10
			`)
			.all();

		if (patterns.length === 0) {
			console.log(chalk.gray(`[SkillFactory] No strong patterns detected yet.`));
			return [];
		}

		console.log(
			chalk.green(`[SkillFactory] Detected ${patterns.length} potential skill patterns.`),
		);
		return patterns;
	}

	/**
	 * Generates a full .aizen skill file based on a pattern.
	 */
	async generateAizenSkill(pattern: { action: string; target: string }): Promise<string> {
		const skillId = `${pattern.action.toLowerCase()}-${path.basename(pattern.target, path.extname(pattern.target)).toLowerCase()}`;
		const skillPath = path.join(this.projectDir, "skills", `${skillId}.md`);

		const _prompt = `Create an Aizen-Gate Skill definition for:
Action: ${pattern.action}
Target: ${pattern.target}

The skill should automate this repetitive task using standard shell commands or node scripts.
Respond ONLY with the Markdown content following the .aizen skill format (YAML frontmatter + Instructions).
Name the skill something elite like "Steel-Fold API" or "Viking-Shield Test".`;

		const distilled = await this.llama.distill(`factory:generate_skill|id:${skillId}`);

		// Fallback template if distillation is purely metadata
		const content = `---
description: Auto-generated skill for ${pattern.action} on ${pattern.target}
---
# ⛩️ ${skillId.toUpperCase()} Skill

This skill was automatically generated by the Aizen-Gate Skill Factory.

## 🏹 Strategy
1. Identify target file: ${pattern.target}
2. Execute action: ${pattern.action}
3. Verify integrity.

## 📜 Execution
${distilled || "// Auto-generated steps go here"}
`;

		if (!fs.existsSync(path.dirname(skillPath))) {
			fs.mkdirSync(path.dirname(skillPath), { recursive: true });
		}

		fs.writeFileSync(skillPath, content);
		console.log(chalk.green(`[SkillFactory] Generated new skill: ${skillId}.md`));
		return skillPath;
	}
}

export const getSkillFactory = (dir: string) => new SkillFactory(dir);
