import fs from "node:fs";
import fsPromises from "node:fs/promises";
import path from "node:path";
import chalk from "chalk";
import yaml from "js-yaml";

export class ManifestGenerator {
	private projectRoot: string;
	private manifestPath: string;
	private devDir: string;

	constructor(projectRoot: string) {
		this.projectRoot = projectRoot;
		this.manifestPath = path.join(projectRoot, "CURRENT_SPRINT.md");
		this.devDir = path.join(projectRoot, "kanban", "dev");
	}

	async updateManifest(): Promise<void> {
		if (!fs.existsSync(this.devDir)) return;

		const files = fs.readdirSync(this.devDir).filter((f) => f.endsWith(".md"));
		if (files.length === 0) {
			try {
				if (fs.existsSync(this.manifestPath)) {
					await fsPromises.unlink(this.manifestPath);
				}
			} catch (err) {
				console.error(`[Kanban] Failed to remove manifest: ${(err as Error).message}`);
			}
			return;
		}

		let manifest = `# 🌀 CURRENT SPRINT CONTEXT\n\n`;
		manifest += `> [!NOTE]\n`;
		manifest += `> This file is auto-generated by Kanban-Agent. It represents the active development context for AI assistance.\n\n`;

		for (const file of files) {
			const content = fs.readFileSync(path.join(this.devDir, file), "utf8");
			const fmMatch = content.match(/---\n([\s\S]*?)\n---/);
			const titleMatch = content.match(/# (.*)/);
			const title = titleMatch ? titleMatch[1] : file;

			manifest += `## 🛠️ ACTIVE TASK: ${title}\n`;

			if (fmMatch) {
				const fm = yaml.load(fmMatch[1]) as any;
				manifest += `- **ID**: \`${fm.id}\`\n`;
				manifest += `- **Priority**: ${fm.priority}\n`;
				manifest += `- **Assignee**: ${fm.assignee}\n`;
			}

			// Extract description and ACs
			const acMatch = content.match(/## Acceptance Criteria \(AC\)([\s\S]*?)(##|\n\n|$)/i);
			if (acMatch) {
				manifest += `\n### ✅ Acceptance Criteria\n${acMatch[1].trim()}\n`;
			}

			const scopeMatch = content.match(/## 🎯 Scope & Impact([\s\S]*?)(---|$)/);
			if (scopeMatch) {
				manifest += `\n### 📝 Scope & Impact\n${scopeMatch[1].trim()}\n`;
			}

			manifest += `\n---\n\n`;
		}

		await fsPromises.writeFile(this.manifestPath, manifest);
		console.log(chalk.blue(`[Kanban] Updated ${path.basename(this.manifestPath)}`));
	}
}
