const fs = require("fs-extra");
const path = require("path");
const chalk = require("chalk");

/**
 * Aizen-Gate built-in documentation generator.
 * Scaffolds the minimum viable docs requested by `az-docs.md`.
 */
async function generateDocs(projectRoot) {
	console.log(chalk.magenta.bold("\n--- [DOCS] Generating Project Documentation ---\n"));

	// Default directory mapping logic checks
	const docsDir = path.join(projectRoot, "docs");
	const saSharedDir = path.join(projectRoot, "aizen-gate", "shared");

	try {
		await fs.ensureDir(docsDir);

		// 1. Generate ADR Template
		const adrDir = path.join(docsDir, "adr");
		await fs.ensureDir(adrDir);
		const adrTemplate = `# ADR 001: Initial Architecture

## Status
Accepted

## Context
We need a robust multi-agent architecture to manage software development.
Aizen-Gate was chosen to enforce the Scrum framework.

## Decision
Adopt Aizen-Gate state schema (project.md, memory.md, state.md).

## Consequences
Pros: AI agents have standardized context.
Cons: Requires maintaining markdown files alongside code.
`;
		await fs.writeFile(path.join(adrDir, "001-initial-architecture.md"), adrTemplate);
		console.log(chalk.green("✓ Created Base ADR Document"));

		// 2. Generate API Docs Template
		const apiFile = path.join(docsDir, "api-reference.md");
		const apiTemplate = `# API Reference

> Run \`npx superagent map\` to populate realistic API endpoints based on the repo structure.

## Authentication
Identify your authentication strategy here.

## Endpoints
*(To be generated by [DOCS] agent analyzing /api routes)*
`;
		await fs.writeFile(apiFile, apiTemplate);
		console.log(chalk.green("✓ Created API Reference Skeleton"));

		// 3. Generate User Guide
		const guideFile = path.join(docsDir, "user-guide.md");
		const guideTemplate = `# User Guide

## Overview
This application is managed by Aizen-Gate.

## Getting Started
1. Clone the repository
2. Run \`npx superagent start\` to initialize context
3. Run \`npx superagent auto\` to implement features
`;
		await fs.writeFile(guideFile, guideTemplate);
		console.log(chalk.green("✓ Created User Guide"));

		console.log(
			chalk.magenta(
				"\n[DOCS] Documentation scaffolding complete. The agents can now populate these files dynamically.",
			),
		);
		return { success: true };
	} catch (err) {
		console.error(chalk.red(`[DOCS] Documentation generation failed: ${err.message}`));
		return { success: false, error: err.message };
	}
}

module.exports = { generateDocs };
