const fs = require('fs-extra');
const path = require('path');
const chalk = require('chalk');

/**
 * Aizen-Gate Codebase Mapper
 * Scans the project directory to build a structural map (Architecture, Stack, APIs).
 */
async function mapCodebase(projectRoot) {
    console.log(chalk.blue.bold('\n--- [SA] Mapping Codebase Architecture ---\n'));

    const map = {
        structure: {},
        techStack: [],
        apiEndpoints: [],
        dataModels: []
    };

    // 1. Scan directory structure (depth 2)
    const scanDir = (dir, depth = 0) => {
        if (depth > 2) return;
        const items = fs.readdirSync(dir);
        for (const item of items) {
            if (item.startsWith('.') || item === 'node_modules') continue;
            const fullPath = path.join(dir, item);
            const isDir = fs.statSync(fullPath).isDirectory();
            
            if (isDir) {
                map.structure[item] = [];
                scanDir(fullPath, depth + 1);
            } else if (item.endsWith('.py')) {
                // Python Mapping Engine logic
                const pyContent = fs.readFileSync(fullPath, 'utf8');
                const classes = [...pyContent.matchAll(/^class\s+([A-Za-z0-9_]+)/gm)].map(m => m[1]);
                const defs = [...pyContent.matchAll(/^def\s+([A-Za-z0-9_]+)/gm)].map(m => m[1]);
                
                if (classes.length > 0 || defs.length > 0) {
                    map.structure[`${item} (Python)`] = { classes, defs };
                }
            }
        }
    };

    try {
        scanDir(projectRoot);

        // 2. Build Structural Markdown
        let output = `# Project Architecture Map\n\nGenerated by Aizen-Gate @[ARCH] on ${new Date().toISOString().split('T')[0]}\n\n`;
        
        output += `## 🏗️ Directory Structure\n\n`;
        Object.entries(map.structure).forEach(([key, val]) => {
            if (Array.isArray(val)) {
                output += `- **/${key}**\n`;
            } else {
                output += `- **${key}**\n`;
                if (val.classes && val.classes.length > 0) output += `  - Classes: ${val.classes.join(', ')}\n`;
                if (val.defs && val.defs.length > 0) output += `  - Methods/Functions: ${val.defs.join(', ')}\n`;
            }
        });

        output += `\n## 🛠️ Inferred Component Map\n\n`;
        if (fs.existsSync(path.join(projectRoot, 'src'))) {
            output += `- **Frontend/Source**: \`/src\` identified.\n`;
        }
        if (fs.existsSync(path.join(projectRoot, 'api')) || fs.existsSync(path.join(projectRoot, 'server'))) {
            output += `- **Backend/API**: API layer identified.\n`;
        }
        if (fs.existsSync(path.join(projectRoot, 'tests'))) {
            output += `- **Testing**: Test suite identified.\n`;
        }

        const mapPath = path.join(projectRoot, 'aizen-gate/shared/architecture-map.md');
        const projectMdPath = path.join(projectRoot, 'aizen-gate/shared/project.md');
        
        await fs.ensureDir(path.dirname(mapPath));
        await fs.writeFile(mapPath, output);
        
        if (fs.existsSync(projectMdPath)) {
             let projContent = await fs.readFile(projectMdPath, 'utf8');
             if (!projContent.includes('## Inferred Architecture')) {
                 projContent += `\n\n## Inferred Architecture\n*Generated by \`za-map\`*\n\n${output}`;
                 await fs.writeFile(projectMdPath, projContent);
             }
        }

        console.log(chalk.green(`[SA] Codebase map generated at: ${mapPath} and updated project.md`));
        return { success: true, path: mapPath };

    } catch (error) {
        console.error(chalk.red(`[SA] Mapping failed: ${error.message}`));
        return { success: false, error: error.message };
    }
}

module.exports = { mapCodebase };
